add userId to endpoint for homepage #119
GSG-K3/rooms-booker pull request #139
Opened 2020-06-16 11:30 UTC by tasneembhiri

2020-06-16 12:46 UTC, yaqootturman requested changes

2020-06-16 12:46 UTC, yaqootturman commented on client/src/components/Common/Header/Header.js
> +import { withRouter } from 'react-router'
can you explain? or document this!

2020-06-17 07:28 UTC, yaqootturman approved these changes

2020-06-17 07:32 UTC, Hanan795 approved these changes

2020-06-17 07:33 UTC, merged

2020-06-17 09:27 UTC, 11janci reviewed
Pls see my comments [here](https://github.com/GSG-K3/rooms-booker/pull/93#pullrequestreview-411648157) about the check API. Would be good if you guys managed to refactor that (of course not in this PR)

2020-06-17 09:27 UTC, 11janci commented on client/src/components/Common/Header/Header.js
> +  show = ()=> {
not a very good name as it doesn't say what it's supposed to show, and actually does not show anything - `redirectToHome` or sth similar would be better.

2020-06-17 09:27 UTC, 11janci commented on client/src/components/Layout/Login/Login.js
> +        this.setState({userId: userId})
do you really need to put this into the state? Seems like it is not used anywhere (unless I'm missing sth)

2020-06-17 09:27 UTC, 11janci commented on client/src/components/Common/Header/Header.js
> +          <img className='profile' src={Profile} alt='profile' onClick={this.show}/></Link></div>
seems there is some redundancy here. You have a link to the user's home page, but then you have the onClick where you do the redirect manually. If the `onClick` is being used, you should be able to remove the Link and just keep the img.