Header Menu
GSG-K3/rooms-booker pull request #152
Opened 2020-06-23 12:50 UTC by aboodswiti

2020-06-23 13:48 UTC, bayanseder approved these changes

2020-06-24 06:14 UTC, yaqootturman requested changes

2020-06-24 06:14 UTC, yaqootturman commented on client/src/components/Common/Header/Header.js
> +  handleClickOutside = (event) => {
document this

2020-06-24 06:14 UTC, yaqootturman commented on client/src/components/Common/Header/Header.js
> +  handleClickOutside = (event) => {
In the Booking form page there is a 'logout' word from the previous version!

2020-06-24 11:37 UTC, yaqootturman approved these changes

2020-06-24 12:27 UTC, merged

2020-06-24 16:32 UTC, 11janci reviewed
The overall mechanism can be simplified. You have the `handleButtonClick()` method that calls the `check` API and sets the `success` variable, based on which you display either `Home` or `Login`. But then, once the user clicks on Home/Login, you call the `check` API again to determine where to redirect. That's inefficient and unnecessary. It is true that the session might expire between the initial check and the redirect, however that should be handled by whatever component it is redirected to - any API calls in that component should fail on 401/403 and the component should in that case redirect to Login. As I mentioned before, the `check` API is really unfortunate, however it's too late to refactor that now.

Related to this is another problem, and that is that you do all of this in button's onclick handlers. So when a user clicks on the menu, you call the API, which could take seconds to respond, rendering the application unresponsive. Instead, the `check` API should be called in the `componentDidMount()` method once and then follow the pattern explained above.

2020-06-24 16:32 UTC, 11janci commented on client/src/components/Common/Header/Header.js
> +    this.container = React.createRef();
it'd be good if the name indicated that it is a ref -> `containerRef`

2020-06-24 16:32 UTC, 11janci commented on client/src/components/Common/Header/Header.js
> +          success: success,
better name for `success` would be `isLoggedIn`