create navbar component #21
GSG-K3/rooms-booker pull request #48
Opened 2020-04-23 11:56 UTC by Hanan795

2020-04-23 12:28 UTC, yaqootturman requested changes
So proud of you Hanan, its great step to continue
go on...

2020-04-23 15:21 UTC, yaqootturman approved these changes

2020-04-23 15:21 UTC, yaqootturman commented on client/src/Components/Common Components/NavBar Component/NavBar.jsx
> +import React, { Component } from 'react'
Rename the folder common Components to Common

2020-04-23 15:21 UTC, yaqootturman commented on client/src/Components/Common Components/NavBar Component/NavBar.jsx
> +          <Switch>
Okay, here we can easily link to a new component without link new endpoints

2020-04-23 15:21 UTC, yaqootturman commented on client/src/Components/Common Components/NavBar Component/NavBar.css
> +.navbar-list {
You can add style to the clicked item, you can use state so underline should appear or hidden

2020-04-23 22:49 UTC, Hanan795 commented on client/src/Components/Common Components/NavBar Component/NavBar.jsx
> +          <Switch>
I try, but I didn't can. Hope you to help me in this problem.

2020-04-26 10:20 UTC, yaqootturman commented on client/src/Components/CommonComponents/NavBar Component/NavBar.jsx
> +import React, { Component } from 'react'
Change the jsx extension to js so all of you have the same extension
And the NabBar component folder you should name it by connected letters, and we discussed to name by PascalCase

2020-04-26 10:20 UTC, yaqootturman commented on client/src/Components/CommonComponents/NavBar Component/NavBar.jsx
> +          <Switch>
NO need to use route because we suppose to change the components not routing

2020-04-27 09:06 UTC, hshahwan requested changes

2020-04-27 09:06 UTC, hshahwan commented on client/src/App.js
> +        <NavBar />
test comment

2020-04-27 09:06 UTC, hshahwan commented on client/src/App.js
> +        <NavBar />
@yaqootturman

2020-04-27 09:57 UTC, bayanseder approved these changes

2020-04-27 09:59 UTC, bayanseder approved these changes

2020-04-27 21:18 UTC, tasneembhiri approved these changes

2020-04-28 10:12 UTC, yaqootturman requested changes

2020-04-28 10:12 UTC, yaqootturman commented on client/src/Components/Common/NavBar/NavBar.js
> +              <button className='link' onClick={this.handleEvent}>Event</button>
Events, not Event "the word"

2020-04-28 10:12 UTC, yaqootturman commented on client/src/Components/Common/NavBar/NavBar.js
> +              <button className='link' onClick={this.handleRoom}>Room</button>
Rooms not Room

2020-04-28 10:12 UTC, yaqootturman commented on client/src/Components/Common/NavBar/NavBar.js
> +  handleEvent = () => {
Great! try to use one method to toggle the boolean state rather than two.
preState will help you

2020-04-28 12:00 UTC, yaqootturman requested changes

2020-04-28 12:00 UTC, yaqootturman commented on client/src/components/Common/AvailableRooms/AvailableRooms.js
> +import React, { Component } from 'react'
Delete this Folder AvailableRooms

2020-04-28 12:46 UTC, yaqootturman approved these changes

2020-04-28 19:22 UTC, merged