#23 Eventpage component
GSG-K3/rooms-booker pull request #56
Opened 2020-04-27 14:34 UTC by tasneembhiri

- create eventpage 
  bring event title and event date from database (events frontend-backend)
  add style for eventpage (mobile first)

2020-04-27 15:17 UTC, yaqootturman requested changes

2020-04-27 15:17 UTC, yaqootturman commented on client/src/components/Layout/Events/Events.js
> +
Delete the empty line

2020-04-27 15:17 UTC, yaqootturman commented on client/src/components/Layout/Events/Events.js
> +              <div className="event">
Give each 'event' class more width and add a media query for bigger screens

2020-04-27 15:17 UTC, yaqootturman commented on client/src/components/Layout/Events/Events.js
> +import './Events.css'
The CSS files should not be capital

2020-04-28 10:03 UTC, yaqootturman reviewed
Looks good, fix the conflict and let other members see it

2020-04-28 12:07 UTC, yaqootturman approved these changes

2020-04-28 14:31 UTC, bayanseder approved these changes

2020-04-28 19:18 UTC, Hanan795 approved these changes

2020-04-28 19:57 UTC, merged