chang some names
GSG-K3/rooms-booker pull request #72
Opened 2020-05-05 20:32 UTC by bayanseder

2020-05-05 20:40 UTC, tasneembhiri approved these changes

2020-05-06 11:49 UTC, yaqootturman requested changes

2020-05-06 11:49 UTC, yaqootturman commented on server/database/queries/eventPost.js
> +  dbConniction.query(sql, (err, result) => {
you can delete the condition block

2020-05-07 20:03 UTC, yaqootturman requested changes

2020-05-07 20:03 UTC, yaqootturman commented on client/src/components/Common/BookingForm/Popup.js
> +    console.log(this.props)
Delete the console

2020-05-07 20:03 UTC, yaqootturman commented on server/database/queries/eventPost.js
> +    .then(response => console.log(response.rows))
Delete the promise at all from the query, use controller as a promise and don't send anything here, in the controller you used   res.send() so put this in resolved and message

2020-05-07 20:49 UTC, yaqootturman approved these changes

2020-05-07 20:49 UTC, merged