when we click on the event it goes to eventinfo page #25
GSG-K3/rooms-booker pull request #77
Opened 2020-05-08 22:56 UTC by tasneembhiri

2020-05-10 22:17 UTC, yaqootturman requested changes

2020-05-10 22:17 UTC, yaqootturman commented on client/src/App.js
> +        <Route exact path = '/event' component={EventInfo}/>
should be specific for one event

2020-05-11 15:32 UTC, yaqootturman approved these changes

2020-05-11 18:40 UTC, aboodswiti approved these changes

2020-05-11 18:41 UTC, merged