create delete event function  #81
GSG-K3/rooms-booker pull request #85
Opened 2020-05-11 22:03 UTC by aboodswiti

Delete Event 
BackEnd & FrontEnd

2020-05-12 08:44 UTC, yaqootturman requested changes

2020-05-12 08:44 UTC, yaqootturman commented on server/database/queries/eventDelete.js
> +  return dbconniction.query(sql).catch((err) => console.log(err));
We talked about this, in queries should not use promise.
you can write return dbconniction.query(sql) and that will be enough

2020-05-12 08:44 UTC, yaqootturman commented on server/controllers/deleteEvent.js
> +  res.send();
So here you send a response for nothing, that means even error will be response

2020-05-12 08:44 UTC, yaqootturman commented on client/src/components/Layout/UserHome/UserHome.js
>        .catch((err) => console.log(err));
Handle the error based on controller response

2020-05-13 12:48 UTC, yaqootturman requested changes

2020-05-13 12:48 UTC, yaqootturman commented on server/controllers/index.js
use router.delete

2020-05-13 12:48 UTC, yaqootturman commented on server/controllers/index.js
and same for axios

2020-05-16 14:44 UTC, tasneembhiri approved these changes

2020-05-16 14:46 UTC, bayanseder approved these changes

2020-05-16 14:51 UTC, yaqootturman approved these changes

2020-05-16 14:52 UTC, merged